package diagnostic

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/eddywiyatno/tmctl/pkg/termutil"
)

// SendTestAlert dispatches a synthetic test alert to Alertmanager to verify end-to-end alerting.
func SendTestAlert(ctx context.Context, alertmanagerURL, recipient string) error {
	termutil.Header("Dispatching Synthetic Verification Alert")

	if alertmanagerURL == "" {
		alertmanagerURL = "http://localhost:9093"
	}
	alertmanagerURL = strings.TrimRight(alertmanagerURL, "/")

	termutil.Info("Alertmanager Endpoint : %s", alertmanagerURL)
	if recipient != "" {
		termutil.Info("Target Recipient      : %s", recipient)
	}

	// Construct Prometheus/Alertmanager v2 alert payload
	now := time.Now().UTC()
	payload := []map[string]interface{}{
		{
			"labels": map[string]string{
				"alertname": "TomcatSyntheticHealthCheck",
				"severity":  "warning",
				"instance":  "tmctl-verification-probe",
				"job":       "tomcat-monitoring-test",
			},
			"annotations": map[string]string{
				"summary":     "Synthetic Alert Pipeline Health Check Verification",
				"description": fmt.Sprintf("Synthetic alert generated by tmctl diagnostic test-alert at %s. Verification succeeded.", now.Format(time.RFC3339)),
				"recipient":   recipient,
			},
			"startsAt": now.Format(time.RFC3339),
			"endsAt":   now.Add(10 * time.Minute).Format(time.RFC3339),
		},
	}

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("failed to encode alert payload: %w", err)
	}

	endpoint := alertmanagerURL + "/api/v2/alerts"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(payloadBytes))
	if err != nil {
		return fmt.Errorf("failed to create http request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to connect to Alertmanager at '%s': %w", endpoint, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusAccepted {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("Alertmanager returned HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}

	termutil.Success("Synthetic alert successfully submitted to Alertmanager (HTTP %d)", resp.StatusCode)
	termutil.Info("Check your notification destination (Mailpit / Postfix relay) to verify receipt.")
	return nil
}
